### ISSUE TITLE
Exercise 1, Task 4, #8

### ISSUE THREAD

**Issue by blgorman** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#103]
**Describe the bug**
YAML is incorrect as shown, immediately fails on build, warns in the editor as typed

**HOL or Workshop Document**
Hands-On-Lab

**To Reproduce**
Create any one of your three docker yaml files.
Add the YAML as shown:

```YAML
# Build and push Docker image with Build (do not push on PR)
# https://github.com/docker/build-push-action
- name: Build and push Docker image
  working-directory: content-web
  uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
  with:
    file: ./content-web/Dockerfile                      # <-- Add these
    context: ./content-web                              # <-- two lines
    push: ${{ github.event_name != 'pull_request' }}
    tags: ${{ steps.meta.outputs.tags }}
    labels: ${{ steps.meta.outputs.labels }}
```
The line "working-directory" will fail the action and warns that it is not possible

![broken](https://user-images.githubusercontent.com/785214/153345922-ce30c30d-d936-45b7-8da4-907d59a4821f.jpg)

**Expected behavior**
Action would not fail

**Solution**
Fix that yaml to be:

```YAML
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: ./content-web/Dockerfile
          context: ./content-web
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```
![fixed](https://user-images.githubusercontent.com/785214/153346408-fff2c144-d270-4563-9f3d-bca48ee01ff9.jpg)
