### ISSUE TITLE
Exercise 3, Task 3, Step 11 - YAML is incorrect and corrected YAML will not run to completion

### ISSUE THREAD

**Issue by blgorman** [microsoft/MCW-Continuous-delivery-in-Azure-DevOps#109]
**Describe the bug**
ADO YAML is not working, and I am unable to determine the cause or fix.  It is possible this is on my end but I do believe I've completed all of the required instructions correctly.

Additionally, ADO Yaml in Exercise 3, Task 3, Step 9 has a typo that is easily corrected and has the correct version listed later in the document.

What is first shown is:  

```YAML  
steps:
- task: DockerCompose@0
inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
- task: DockerCompose@0
inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
```  

This should be:

```YAML
steps:
- task: DockerCompose@0
inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'
- task: DockerCompose@0
inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
```  
> Note: `Push services` is listed for both entries.  Note also that the YAML is correct later in the task

**HOL or Workshop Document**
HOL

**Time Frame Needed**
ASAP - could not complete lab

**To Reproduce**
Go to Ex 3, Task 3, and walk through steps 1-11:
Set up your ADO project with all the service principles and github connections
Create the YAML for the ADO deployment
Run the pipeline
Failure for something referencing a docker image in the docker.io registry?

**Expected behavior**
Expected the YAML to work and the pipeline to complete and deploy to Azure.

**Screenshots**

![adoyaml1](https://user-images.githubusercontent.com/785214/153357089-20b4cc9e-475b-4809-a753-a092a4b9c312.png)

![adoyaml2](https://user-images.githubusercontent.com/785214/153357110-5fc04926-52d9-4af9-aa1c-fbdbe866860b.png)
